### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by spacether** [respeaker/respeaker_python_library#20]
Please add a license

**Comment by xiongyihui** [comment]
It's Apache license. You can find it on the header of the .py files. A PR of adding a license file is welcome

**Comment by spacether** [comment]
Please add me as a contributor on the project. I made a branch which adds the license, but I'm unable to add it to github.com per the below error:
remote: Permission to respeaker/respeaker_python_library.git denied

**Comment by xiongyihui** [comment]
just invite you. Another way is to send a pull request.
