### ISSUE TITLE
how can I use the custom model for the wake up words?

### ISSUE THREAD

**Issue by dongcc** [respeaker/respeaker_python_library#27]
Hi,
pocketsphinx support the customized model,
how can I use the custom model for the wake up words within the respeaker library? thanks

**Comment by xiongyihui** [comment]
You can change the code at https://github.com/respeaker/respeaker_python_library/blob/master/respeaker/microphone.py#L123

**Comment by dongcc** [comment]
thanks @xiongyihui , after I customized the hmm with https://github.com/cmusphinx/pocketsphinx/tree/master/model/en-us/en-us on respeaker,
I got following messages after I started the app(the same setting works okay on my Mac):
INFO:mic:Too many delays, 433 in queue
INFO:mic:Too many delays, 434 in queue
INFO:mic:Too many delays, 435 in queue
INFO:mic:Too many delays, 435 in queue
INFO:mic:Too many delays, 437 in queue
INFO:mic:Too many delays, 437 in queue
INFO:mic:Too many delays, 438 in queue
INFO:mic:Too many delays, 439 in queue
...
How can I solve this problem on respeaker?

**Comment by xiongyihui** [comment]
The cpu of the respeaker core 7688 is much weaker than your Mac. You should use a lite acoustic model like https://github.com/respeaker/pocketsphinx-data

**Comment by KillingJacky** [comment]
Will close this issue, please open a new issue if you have further questions.
