### ISSUE TITLE
changing pixel_ring.wait() color

### ISSUE THREAD

**Issue by elpimous** [respeaker/respeaker_python_library#30]
hello, trying some mods, but I don't find how to change color of the pixel_ring.py wait mode.
I'd like to add in pixel_ring.py some functions like  wait_blue, wait_red.... (actual is green) and perhaps, if possible, change speed.
An idea ?

**Comment by xiongyihui** [comment]
If you are using the respeaker core, you can modify the arduino code to change the code. But if you are using the respeaker usb mic array, the color can't be changed yet.

**Comment by elpimous** [comment]
Oh, Ok !
Perhaps one day ?!
Thanks xiongyihui.
