### ISSUE TITLE
offline - Wake up not working

### ISSUE THREAD

**Issue by ghost** [respeaker/respeaker_python_library#31]
I tried it with 2 different microphones (both usb), but the wake up event hasn't been triggered. My Console stuff:
```
daniel@daniel-8o23dad:~/respeaker_python_library$ sudo python examples/offline_voice_assistant.py 
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
INFO:mic:Start detecting
```

So how can I get that offline example working?

**Comment by KillingJacky** [comment]
Hi, the logs you posted here are not enough to address the problem, they just seem all the way ok. You might take the following steps to check your audio configuration:
- sudo alsamixter - to check your volume configuration
- use arecord to record some audio from particular microphone, and check if the captured sound ok

**Comment by KillingJacky** [comment]
Will close this issue, please open a new issue if you have further questions.
