### ISSUE TITLE
Microphone.py question

### ISSUE THREAD

**Issue by auvilink** [respeaker/respeaker_python_library#43]
Hi, there,

I am using Respeaker USB 4 Mic Array (you might have the same mic array) for speech recognition.

This mic array has 6 channel audio output, so which channel does this microphone.py speech recognition actually use?

As far as I understand, the first channel (channel 0) is the one processed for asr, any chance we can use that channel?

Thank you.

**Comment by xiongyihui** [comment]
@auvilink If you just want the first channel, you can use the mono channel firmware. See  https://github.com/respeaker/usb_4_mic_array

**Comment by KillingJacky** [comment]
Will close this issue, please open a new issue if you have further questions.
